### PR TITLE
Gaming: A WIP for the Issue: add a gaming section to budgie-welcome #151

### PR DESCRIPTION
**Pull request by HellBringer419**
Regarding issue #151 

This adds a new "gaming" section under the Install Software drop-down in Budgie Welcome. 
The gaming section contains two gaming clients (Lutris & steam) for now. However, more features (like input mapper and store links) would probably be added later. Hence the WIP.

### CODE REVIEW

**Comment by HellBringer419** [comment]
Hey @ilvipero, nice to meet you. 
I'm okay with working on this given there is enough support. Last time this died out pretty quick; wouldn't want that to happen.
Also, if you want I can add you as a contributor to that fork in case you wanna spice it up.

**Comment by ilvipero** [comment]
@HellBringer419 Thanks for your availability. I have been talking with the team about this and reading other posts such as this. https://github.com/UbuntuBudgie/budgie-welcome/issues/151
Looks you guys had great discussions and the app itself is already visually aligned with the rest of Budgie Welcome. I am not a developer, so won't be able to help you with writing the code but I can help out with communications with our community, and general ideas, direction, and feedback.

**Comment by HellBringer419** [comment]
Would you want me to resolve merge conflicts and keep it here (for merge later) _or_  make code changes after some decision discussions?

**Comment by ilvipero** [comment]
I think it would be good to have a discussion, best if we can use the link I posted above, so that the whole team and community can be involved to give us ideas, and even better someone might jump in and offer to help you.

**Comment by HellBringer419** [comment]
All conflicts resolved. Synced with upstream. 

Awaiting review and merge.

**Comment by fossfreedom** [comment]
Something very odd with this merge request- github says 237 files have changed.

**Comment by HellBringer419** [comment]
That' was because of the 'sync with upstream' ... Reverted it 
(for some reason, commits made in upstream were being shown as my commits)

**Comment by HellBringer419** [comment]
To ensure everything syncs well, I took all updates from upstream, created a new branch and manually did the changes.
Here's the new PR: https://github.com/UbuntuBudgie/budgie-welcome/pull/268
This one will get deleted soon.

**Comment by HellBringer419** [comment]
New PR #268 got merged, closing this.

**Pull request closed without merging**
