### PR TITLE
Create zh_CN.po

### PR DESCRIPTION
**Pull request by eremiter**
Add a Chinese language file.The simplified Chinese language package has been translated.

### CODE REVIEW

**Comment by fossfreedom** [comment]
Hi, thanks for the PR

All translations are managed by transifex. So please join and submit via transifex.

Thx
https://www.transifex.com/ubuntu-budgie/

**Comment by eremiter** [comment]
Hello Sir,
Unable to open, 404 error is displayed.
https://www.transifex.com/ubuntu-budgie/ 

Best regards,
 
From: David Mohammed
Date: 2022-11-04 15:36
To: UbuntuBudgie/budgie-welcome
CC: Budgie; Author
Subject: Re: [UbuntuBudgie/budgie-welcome] Create zh_CN.po (PR #295)
Hi, thanks for the PR
All translations are managed by transifex. So please join and submit via transifex.
Thx
https://www.transifex.com/ubuntu-budgie/

**Comment by fossfreedom** [comment]
https://explore.transifex.com/ubuntu-budgie/budgie-welcome/ is the URL to the welcome project itself

you need to have a transifex account and be logged in probably to use the URL.

**Comment by eremiter** [comment]
Hello David,

It took me 2 days to complete the translation. Please kindly approve it or give me a permission to review it. Thank you.
chinese (zh_CN)

Best regards,
 
From: David Mohammed
Date: 2022-11-04 19:19
To: UbuntuBudgie/budgie-welcome
CC: Budgie; Author
Subject: Re: [UbuntuBudgie/budgie-welcome] Create zh_CN.po (PR #295)
https://explore.transifex.com/ubuntu-budgie/budgie-welcome/ is the URL to the welcome project itself
you need to have a transifex account and be logged in probably to use the URL.
―

**Comment by fossfreedom** [comment]
More than happy to make you a reviewer on transifex - 

I see the following translator members for zh_CN - which one are you?

Harvey Woo [Harvey.Woo](https://www.transifex.com/user/profile/Harvey.Woo/)
Christopher [Ken418](https://www.transifex.com/user/profile/Ken418/)
LiBaogan [LiBaogan](https://www.transifex.com/user/profile/LiBaogan/)
Yazi Tian [Tianyazi](https://www.transifex.com/user/profile/Tianyazi/)
gavin guo [gavinguo](https://www.transifex.com/user/profile/gavinguo/)
John Heart [john_heart](https://www.transifex.com/user/profile/john_heart/)

**Comment by eremiter** [comment]
Hello Sir,

I'am Tianyazi.

Best regards,
 
From: David Mohammed
Date: 2022-11-05 23:19
To: UbuntuBudgie/budgie-welcome
CC: Budgie; Author
Subject: Re: [UbuntuBudgie/budgie-welcome] Create zh_CN.po (PR #295)
More than happy to make you a reviewer on transifex -
I see the following translator members for zh_CN - which one are you?
Harvey Woo Harvey.Woo
Christopher Ken418
LiBaogan LiBaogan
Yazi Tian Tianyazi
gavin guo gavinguo
John Heart john_heart

**Pull request closed without merging**
