### PR TITLE
Update ru.po

### PR DESCRIPTION
**Pull request by JuPlutonic**
To transiflex.
Spell, punctuation, langauge-style, po-file structure & trailing spaces are double checked.

### CODE REVIEW

**Comment by fossfreedom** [comment]
cheers!

**Comment by fossfreedom** [comment]
Apologies - I have had to reject this merge request.

The translation of Russian on transifex is incomplete.  I need a much higher percentage completion rate before pulling the translation into the repository.

If you can help out - please join the team on transifex and translate from there.

https://www.transifex.com/ubuntu-budgie

**Comment by JuPlutonic** [comment]
@fossfreedom have Ubuntu Budgie planned changes on this weekend? I want translate 10-12 files before put them to transiflex? (Sorry all future questions I will ask in Discourse)

**Comment by fossfreedom** [comment]
A new version of budgie-welcome will be released later today.

We will be releasing another version of budgie-welcome next weekend.

Please make the changes on the transifex website itself.

**Pull request merged**
