### PR TITLE
Gaming PR

### PR DESCRIPTION
**Pull request by HellBringer419**
This relates to issue #281 
- There are launch buttons for steam games. And Install for Open-source games.
- YT button now says "Watch"
- Official branded logos for steam and YT are added.
- Coherent colours for buttons
- Launch steam btn uses steam cli
- minor addition to the tool-tip

Behaviour of launch button:

|                                    | Game is installed        | Game is not installed                                                     |
| ------------------------------ | ------------------------------ | --------------------------------------------------------------------------- |
| Steam is installed       | Launch game directly | Show the game's page in store section of steam client |
| Steam is not installed | Opens game page in browser        | Opens game page in browser                     |

Earlier, these changes were not meant to go live in 22.04, but since the work is done, hence the PR.
In case there are problems, changes done by this PR *may* need to be reverted.

Reviewer: 
@fossfreedom

### CODE REVIEW

**Comment by ilvipero** [comment]
Excellent work @HellBringer419 . Thanks for pushing this for 22.04 release.

**Comment by fossfreedom** [comment]
I see the following when pulling in the branch - thoughts?

No steam installed here:

image

**Comment by HellBringer419** [comment]
The branch does have the new images ... I checked on my VM

**Comment by fossfreedom** [comment]
feels like something wasnt checked in - this is what was pulled:

```
dad@dad-TUXEDO-Pulse-15-Gen1:~/development/budgie-welcome$ git pull https://github.com/HellBringer419/budgie-welcome.git gaming-pr
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 38 (delta 27), reused 30 (delta 19), pack-reused 0
Unpacking objects: 100% (38/38), 58.18 KiB | 1.19 MiB/s, done.
From https://github.com/HellBringer419/budgie-welcome
 * branch            gaming-pr  -> FETCH_HEAD
Merge made by the 'ort' strategy.
 budgie-welcome                       |   7 +++++++
 data/config/packages.json            |   3 +++
 data/gaming.html                     |  93 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------
 data/img/logos/steam.png             | Bin 31970 -> 5952 bytes
 data/img/logos/steam_app_icon.png    | Bin 0 -> 47446 bytes
 data/img/logos/youtube.png           | Bin 0 -> 7418 bytes
 data/img/logos/yt_logo_rgb_light.png | Bin 20462 -> 0 bytes
 7 files changed, 88 insertions(+), 15 deletions(-)
 create mode 100644 data/img/logos/steam_app_icon.png
 create mode 100644 data/img/logos/youtube.png
 delete mode 100644 data/img/logos/yt_logo_rgb_light.png
```

**Comment by HellBringer419** [comment]
Even YT launch btn is not there ?
... 
You seem to have the correct changes

**Comment by HellBringer419** [comment]
I removed steam too ... I can see the btns.
It's on focal btw.
Screenshot-New btns

**Comment by fossfreedom** [comment]
The valheim watch link goes to the wrong game - let me know what the correct url is.

**Comment by HellBringer419** [comment]
Valhiem correct yt video
https://m.youtube.com/watch?v=5mHRJ1KFe20

**Comment by HellBringer419** [comment]
Wouldn't that btn in Valhiem.txt install steam .
I believe we should move them to game clients tab but not install steam automatically.
@ilvipero need some opinions.

**Comment by fossfreedom** [comment]
Look closely... the button runs a bit of javascript that changes to the client tools tab.

The config change is simply to determine if the steam button or the launch button is visible

**Comment by HellBringer419** [comment]
got it

**Comment by HellBringer419** [comment]
Done these changes ... Checking on VM

**Comment by HellBringer419** [comment]
Tested on Focal .. Works

**Comment by fossfreedom** [comment]
@HellBringer419 nice work - I've merged.  I don't think the "Install Steam from game-clients" really worked - made the button too wide - so have reduced it back to "Install Steam" again.

I've also fixed the issue where if you were at the bottom of the gaming list, switching tab also put steam on the wrong position in the page - so now we scroll back to steam.

**Comment by ilvipero** [comment]
@HellBringer419 thank you for your dedication and I am glad that with @fossfreedom help, you guys managed to find a way that not only works, but is also very user friendly. 
Can't wait to test it. Thanks!

**Comment by HellBringer419** [comment]
Thanks @fossfreedom  .. You have a great eye for finding errors.

**Pull request merged**
