### PR TITLE
Fixed Alignment and Unterminated Template Literal bug

### PR DESCRIPTION
**Pull request by ShoaibIN**

### CODE REVIEW

**Comment by ShoaibIN** [comment]
#197

**Comment by fossfreedom** [comment]
Did you actually test this?

image

**Comment by ShoaibIN** [comment]
That's not how it was showing me... I probably messed up somewhere

**Comment by ShoaibIN** [comment]
Maybe the live server I'm creating with VSCode is not working. Any idea how can I live test it on windows?
./budgie-welcome --force-session=live -d does not work on windows...

**Comment by fossfreedom** [comment]
Sorry - I don't know - this has only been developed and tested on ubuntu budgie.

**Comment by ShoaibIN** [comment]
Ok, not a problem. I was planning on dual booting a Linux distro tomorrow anyway. I'll fix it then. Don't want my first PR to go this bad. Haha

**Comment by ShoaibIN** [comment]
@fossfreedom hey, I used friend's laptop wiht linux to test. I think it's working now

**Pull request closed without merging**
